kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: nvbandwidth-build
spec:
  runPolicy: Serial
  source:
    dockerfile: |
      FROM nvcr.io/nvidia/cuda:12.4.1-devel-ubi9

      WORKDIR /

      RUN dnf -y install boost-devel cmake make git && dnf clean all && rm -rf /var/cache/yum
      RUN git clone --single-branch --branch=main --depth=1 https://github.com/NVIDIA/nvbandwidth.git
      RUN cd nvbandwidth && cmake . && make && chmod +x nvbandwidth && cp nvbandwidth /usr/bin/nvbandwidth

      ENTRYPOINT [ "nvbandwidth" ]
  strategy:
    dockerStrategy:
      volumes:
      - name: etc-pki-entitlement
        mounts:
        - destinationPath: /etc/pki/entitlement
        source:
          type: Secret
          secret:
            secretName: etc-pki-entitlement
      from:
        kind: "ImageStreamTag"
        name: "cuda:12.4.1-devel-ubi9"
  output:
    to:
      kind: "ImageStreamTag"
      name: "nvbandwidth:latest"
